export default function HomePage() {
  return (
    <main className="container">
      <p className="label">
        ReadySpace WebSpace Headless WordPress Starter
      </p>

      <h1>Your headless WordPress frontend is running</h1>

      <p>
        This page is generated by Next.js and hosted on ReadySpace WebSpace
        Premium.
      </p>

      <p>
        Create and publish a WordPress post titled:
        <strong> Hello from ReadySpace Headless WordPress</strong>
      </p>

      <p>
        <a href="/hello-from-readyspace-headless-wordpress/">
          Open the WordPress test post
        </a>
      </p>
    </main>
  );
}